In [1]:
## Numpy is a fundamental library for scientific computations,it provide support for arrays, matrices etc.

!pip install numpy

In [3]:
import numpy as np
# creating 1d array
arr1 = np.array([1,2,3,4])
print(arr1)
# shape of array
print(np.shape(arr1))

[1 2 3 4]
(4,)


In [6]:
## reshaping the array
arr2 = np.array([1,2,3,4])
arr2 = arr2.reshape(1,4)
print(arr2)

## arange
arr3 = np.arange(0,10,2).reshape(5,1)
print(arr3)

[[1 2 3 4]]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [9]:
## inbuild functions 
# ones create matrix with all value as 1
np.ones((1,3))
# indentity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# Attributes of np array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:",arr)
print('\n')
print("Shape:",arr.shape)
print("dimension:",arr.ndim)
print("Size:(no of elements):",arr.size)
print("data type:",arr.dtype)
print("item size:", arr.itemsize)


Array: [[1 2 3]
 [4 5 6]]


Shape: (2, 3)
dimension: 2
Size:(no of elements): 6
data type: int64
item size: 8


In [13]:
## vectorized operations
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([20,30,40,50,90,100])

# element wise addition
print("Addition:",arr1+arr2)
# element wise substraction
print("Addition:",arr1-arr2)
# element wise multiplication
print("Addition:",arr1*arr2)
# element wise division
print("Addition:",arr1/arr2)

Addition: [ 21  32  43  54  95 106]
Addition: [-19 -28 -37 -46 -85 -94]
Addition: [ 20  60 120 200 450 600]
Addition: [0.05       0.06666667 0.075      0.08       0.05555556 0.06      ]


In [15]:
## Universal functions
arr = np.array([1,2,3,4])
## square root
print(np.sqrt(arr))
## exponential
print(np.exp(arr))
## natural log
print(np.log(arr))
## sine
print(np.sin(arr))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [20]:
##  slicing and indexing 
mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(mat[0:2,2:])
print(mat[1:,3:])
print(mat[0,0])

## modification in array
mat[0,0] = 10

[[3 4]
 [7 8]]
[[ 8]
 [12]]
1


In [23]:
# statistical concepts
data = np.arange(1,11)
print(data)
# mean
mean = np.mean(data)
print(mean)
# median 
median = np.median(data)
print(median)
# standard deviation
std = np.std(data)
print(std)
# variance
variance = np.var(data)
print(variance)

[ 1  2  3  4  5  6  7  8  9 10]
5.5
5.5
2.8722813232690143
8.25


In [25]:
## logical operations
data > 5 ## give array in true false where the condition matches
data[data>5] ## irectly give array with all elements that matches the condition

array([ 6,  7,  8,  9, 10])