#### Creating wordEmbedding Layer

In [1]:
### Via OHE
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
Sentences = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tree',
    'I am a good boy',
    'I am a good developer',
    'Userstand the meaning of words',
    'i will become a business Man'
]

In [3]:
## vocabulary size
voc_size = 10000

In [4]:
one_hot_rep = [one_hot(words,voc_size) for words in Sentences]

In [5]:
one_hot_rep

[[6264, 7697, 2974, 8565],
 [6264, 7697, 2974, 2187],
 [6264, 1321, 2974, 7092],
 [1804, 752, 7468, 1568, 7212],
 [1804, 752, 7468, 1568, 8949],
 [3522, 6264, 4591, 2974, 6762],
 [1804, 1774, 2501, 7468, 8359, 4304]]

In [6]:
##word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [19]:
## so right know we have a sentences with different lengths so first of all make them as same size and to do that we can take maximun length(specifies the vocabulary) and we can add zeros
## either at the front using 'pre' or at end using 'post' that why we are using a pad_sequence

words_length = 8
embedding_doc =pad_sequences(one_hot_rep,padding='pre',maxlen=words_length)
print(embedding_doc)

[[   0    0    0    0 6264 7697 2974 8565]
 [   0    0    0    0 6264 7697 2974 2187]
 [   0    0    0    0 6264 1321 2974 7092]
 [   0    0    0 1804  752 7468 1568 7212]
 [   0    0    0 1804  752 7468 1568 8949]
 [   0    0    0 3522 6264 4591 2974 6762]
 [   0    0 1804 1774 2501 7468 8359 4304]]


In [20]:
## feature representation
dim=10

In [ ]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=words_length))
model.compile('adam','mse')

In [25]:
model.build(input_shape=(None, words_length))

In [26]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.predict(embedding_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 288ms/step


array([[[-2.60941386e-02,  4.76663187e-03, -8.40567052e-04,
         -3.91693115e-02,  4.53843214e-02,  1.99594609e-02,
          3.37183475e-03, -1.05809681e-02,  1.50008909e-02,
          2.24004425e-02],
        [-2.60941386e-02,  4.76663187e-03, -8.40567052e-04,
         -3.91693115e-02,  4.53843214e-02,  1.99594609e-02,
          3.37183475e-03, -1.05809681e-02,  1.50008909e-02,
          2.24004425e-02],
        [-2.60941386e-02,  4.76663187e-03, -8.40567052e-04,
         -3.91693115e-02,  4.53843214e-02,  1.99594609e-02,
          3.37183475e-03, -1.05809681e-02,  1.50008909e-02,
          2.24004425e-02],
        [-2.60941386e-02,  4.76663187e-03, -8.40567052e-04,
         -3.91693115e-02,  4.53843214e-02,  1.99594609e-02,
          3.37183475e-03, -1.05809681e-02,  1.50008909e-02,
          2.24004425e-02],
        [ 3.14152353e-02, -3.88480052e-02, -3.42171416e-02,
         -4.63890210e-02,  3.67951728e-02, -1.64671913e-02,
          2.64380313e-02,  8.60650465e-03, -4.448739